#!/bin/bash

# Verificação do sistema
if [ -f /etc/debian_version ]; then
    echo "Sistema Debian!"
else
    echo "[ERRO] Distribuição ou sistema incompatível com o script. Certifique-se que o sistema é Linux e Debian."
    exit 1
fi
